export const GET_ALL_CLASSES_REQUEST = 'GET_ALL_CLASSES_REQUEST'
export const GET_ALL_CLASSES_SUCCESS = 'GET_ALL_CLASSES_SUCCESS'
export const GET_ALL_CLASSES_FAIL = 'GET_ALL_CLASSES_FAIL'
export const GET_ALL_CLASSES_RESET = 'GET_ALL_CLASSES_RESET'

export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST'
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS'
export const DELETE_CLASS_FAIL = 'DELETE_CLASS_FAIL'
export const DELETE_CLASS_RESET = 'DELETE_CLASS_RESET'

export const UPDATE_CLASS_REQUEST = 'UPDATE_CLASS_REQUEST'
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS'
export const UPDATE_CLASS_FAIL = 'UPDATE_CLASS_FAIL'
export const UPDATE_CLASS_RESET = 'UPDATE_CLASS_RESET'

export const GET_ALL_MY_CLASSES_REQUEST = 'GET_ALL_MY_CLASSES_REQUEST'
export const GET_ALL_MY_CLASSES_SUCCESS = 'GET_ALL_MY_CLASSES_SUCCESS'
export const GET_ALL_MY_CLASSES_FAIL = 'GET_ALL_MY_CLASSES_FAIL'
export const GET_ALL_MY_CLASSES_RESET = 'GET_ALL_MY_CLASSES_RESET'

export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST'
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS'
export const CREATE_CLASS_FAIL = 'CREATE_CLASS_FAIL'
export const CREATE_CLASS_RESET = 'CREATE_CLASS_RESET'

export const GET_CLASS_BY_ID_REQUEST = 'GET_CLASS_BY_ID_REQUEST'
export const GET_CLASS_BY_ID_SUCCESS = 'GET_CLASS_BY_ID_SUCCESS'
export const GET_CLASS_BY_ID_FAIL = 'GET_CLASS_BY_ID_FAIL'
export const GET_CLASS_BY_ID_RESET = 'GET_CLASS_BY_ID_RESET'

export const JOIN_CLASS_BY_CODE_REQUEST = 'JOIN_CLASS_BY_CODE_REQUEST'
export const JOIN_CLASS_BY_CODE_SUCCESS = 'JOIN_CLASS_BY_CODE_SUCCESS'
export const JOIN_CLASS_BY_CODE_FAIL = 'JOIN_CLASS_BY_CODE_FAIL'
export const JOIN_CLASS_BY_CODE_RESET = 'JOIN_CLASS_BY_CODE_RESET'

export const GET_ALL_STUDENTS_REQUEST = 'GET_ALL_STUDENTS_REQUEST'
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS'
export const GET_ALL_STUDENTS_FAIL = 'GET_ALL_STUDENTS_FAIL'
export const GET_ALL_STUDENTS_RESET = 'GET_ALL_STUDENTS_RESET'

export const GET_ALL_TEACHERS_REQUEST = 'GET_ALL_CLASS_REQUEST'
export const GET_ALL_TEACHERS_SUCCESS = 'GET_ALL_CLASS_SUCCESS'
export const GET_ALL_TEACHERS_FAIL = 'GET_ALL_CLASS_FAIL'
export const GET_ALL_TEACHERS_RESET = 'GET_ALL_TEACHERS_RESET'

export const SEND_INVITATION_BY_EMAIL_REQUEST = 'SEND_INVITATION_BY_EMAIL_REQUEST'
export const SEND_INVITATION_BY_EMAIL_SUCCESS = 'SEND_INVITATION_BY_EMAIL_SUCCESS'
export const SEND_INVITATION_BY_EMAIL_FAIL = 'SEND_INVITATION_BY_EMAIL_FAIL'
export const SEND_INVITATION_BY_EMAIL_RESET = 'SEND_INVITATION_BY_EMAIL_RESET'

export const GET_ALL_TYPE_STUDENTS_REQUEST = 'GET_ALL_TYPE_STUDENTS_REQUEST'
export const GET_ALL_TYPE_STUDENTS_SUCCESS = 'GET_ALL_TYPE_STUDENTS_SUCCESS'
export const GET_ALL_TYPE_STUDENTS_FAIL = 'GET_ALL_TYPE_STUDENTS_FAIL'
export const GET_ALL_TYPE_STUDENTS_RESET = 'GET_ALL_TYPE_STUDENTS_RESET'