export const GET_ALL_CLASSES_REQUEST = 'GET_ALL_CLASSES_REQUEST'
export const GET_ALL_CLASSES_SUCCESS = 'GET_ALL_CLASSES_SUCCESS'
export const GET_ALL_CLASSES_FAIL = 'GET_ALL_CLASSES_FAIL'
export const GET_ALL_CLASSES_RESET = 'GET_ALL_CLASSES_RESET'

export const DELETE_CLASS_REQUEST = 'DELETE_CLASS_REQUEST'
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS'
export const DELETE_CLASS_FAIL = 'DELETE_CLASS_FAIL'
export const DELETE_CLASS_RESET = 'DELETE_CLASS_RESET'

export const UPDATE_CLASS_REQUEST = 'UPDATE_CLASS_REQUEST'
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS'
export const UPDATE_CLASS_FAIL = 'UPDATE_CLASS_FAIL'
export const UPDATE_CLASS_RESET = 'UPDATE_CLASS_RESET'

export const GET_ALL_MY_CLASSES_REQUEST = 'GET_ALL_MY_CLASSES_REQUEST'
export const GET_ALL_MY_CLASSES_SUCCESS = 'GET_ALL_MY_CLASSES_SUCCESS'
export const GET_ALL_MY_CLASSES_FAIL = 'GET_ALL_MY_CLASSES_FAIL'
export const GET_ALL_MY_CLASSES_RESET = 'GET_ALL_MY_CLASSES_RESET'

export const CREATE_CLASS_REQUEST = 'CREATE_CLASS_REQUEST'
export const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS'
export const CREATE_CLASS_FAIL = 'CREATE_CLASS_FAIL'
export const CREATE_CLASS_RESET = 'CREATE_CLASS_RESET'

export const GET_ALL_STUDENTS_REQUEST = 'GET_ALL_STUDENTS_REQUEST'
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS'
export const GET_ALL_STUDENTS_FAIL = 'GET_ALL_STUDENTS_FAIL'
export const GET_ALL_STUDENTS_RESET = 'GET_ALL_STUDENTS_RESET'

export const GET_ALL_TEACHERS_REQUEST = 'GET_ALL_CLASS_REQUEST'
export const GET_ALL_TEACHERS_SUCCESS = 'GET_ALL_CLASS_SUCCESS'
export const GET_ALL_TEACHERS_FAIL = 'GET_ALL_CLASS_FAIL'
export const GET_ALL_TEACHERS_RESET = 'GET_ALL_TEACHERS_RESET'