export const GET_ALL_GRADE_COMPOSITION_REQUEST = 'GET_ALL_GRADE_COMPOSITION_REQUEST'
export const GET_ALL_GRADE_COMPOSITION_SUCCESS = 'GET_ALL_GRADE_COMPOSITION_SUCCESS'
export const GET_ALL_GRADE_COMPOSITION_FAIL = 'GET_ALL_GRADE_COMPOSITION_FAIL'
export const GET_ALL_GRADE_COMPOSITION_RESET = 'GET_ALL_GRADE_COMPOSITION_RESET'

export const GET_ALL_REVIEW_BY_STUDENT_ID_REQUEST = 'GET_ALL_REVIEW_BY_STUDENT_ID_REQUEST'
export const GET_ALL_REVIEW_BY_STUDENT_ID_SUCCESS = 'GET_ALL_REVIEW_BY_STUDENT_ID_SUCCESS'
export const GET_ALL_REVIEW_BY_STUDENT_ID_FAIL = 'GET_ALL_REVIEW_BY_STUDENT_ID_FAIL'
export const GET_ALL_REVIEW_BY_STUDENT_ID_RESET = 'GET_ALL_REVIEW_BY_STUDENT_ID_RESET'

export const GET_ALL_REVIEW_REQUEST = 'GET_ALL_REVIEW_REQUEST'
export const GET_ALL_REVIEW_SUCCESS = 'GET_ALL_REVIEW_SUCCESS'
export const GET_ALL_REVIEW_FAIL = 'GET_ALL_REVIEW_FAIL'
export const GET_ALL_REVIEW_RESET = 'GET_ALL_REVIEW_RESET'

export const GET_ALL_COMMENT_REQUEST = 'GET_ALL_COMMENT_REQUEST'
export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS'
export const GET_ALL_COMMENT_FAIL = 'GET_ALL_COMMENT_FAIL'
export const GET_ALL_COMMENT_RESET = 'GET_ALL_COMMENT_RESET'