export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST'
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS'
export const USER_CHANGE_PASSWORD_FAIL = 'USER_CHANGE_PASSWORD_FAIL'
export const USER_CHANGE_PASSWORD_RESET = 'USER_CHANGE_PASSWORD_RESET'

export const USER_GET_PROFILE_REQUEST = 'USER_GET_PROFILE_REQUEST'
export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS'
export const USER_GET_PROFILE_FAIL = 'USER_GET_PROFILE_FAIL'
export const USER_GET_PROFILE_RESET = 'USER_GET_PROFILE_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'
